# Generated by Django 3.2 on 2021-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0006_alter_tcomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
