# Generated by Django 3.2 on 2021-04-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0008_treply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treply',
            name='TComment',
        ),
        migrations.AddField(
            model_name='tcomment',
            name='TReply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='school_management_app.treply'),
        ),
    ]
