# Generated by Django 3.2 on 2021-04-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0010_alter_tcomment_treply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcomment',
            old_name='TReply',
            new_name='reply',
        ),
    ]
