# Generated by Django 3.2 on 2021-04-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0011_rename_treply_tcomment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TReply',
        ),
    ]
