# Generated by Django 3.2 on 2021-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0012_delete_treply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
