# Generated by Django 3.2 on 2021-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0013_alter_tcomment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tnews',
            name='ndate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
