# Generated by Django 3.2 on 2021-04-29 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0014_auto_20210429_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scomment',
            old_name='news',
            new_name='News',
        ),
        migrations.RemoveField(
            model_name='scomment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='scomment',
            name='name',
        ),
        migrations.AddField(
            model_name='scomment',
            name='count',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='scomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='school_management_app.scomment'),
        ),
        migrations.AddField(
            model_name='scomment',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
