# Generated by Django 3.2 on 2021-05-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0018_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='students',
            new_name='student_id',
        ),
    ]
