# Generated by Django 3.2 on 2021-05-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0020_auto_20210501_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
