# Generated by Django 3.2 on 2021-05-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0023_notificationparents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ntext', models.TextField()),
                ('ntitle', models.TextField(max_length=4000)),
                ('ndate', models.DateTimeField(auto_now_add=True)),
                ('pic', models.FileField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default='1')),
                ('PNews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='school_management_app.pnews')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='school_management_app.pcomment')),
                ('staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
