# Generated by Django 3.2 on 2021-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0024_pcomment_pnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstudent',
            old_name='leave_date',
            new_name='leave_start_date',
        ),
        migrations.AddField(
            model_name='leavereportstudent',
            name='leave_end_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
