# Generated by Django 3.2 on 2021-04-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcomment',
            name='staff_id',
        ),
    ]
