# Generated by Django 3.2 on 2021-04-26 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0002_remove_tcomment_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcomment',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
